# Site settings
title: "Shao Cheng"
email: "youremail@example.com"
description: "Personal website of Shao Cheng"
baseurl: "" # Base URL for the site, keep it empty for root
url: "https://yourusername.github.io" # Your GitHub Pages URL
twitter_username: "" # Optional, if you want to add your social media
github_username: "yourusername" # Your GitHub username
google_analytics: "" # Your Google Analytics tracking ID

# Author settings
author:
  name: "Shao Cheng"
  avatar: "/assets/img/avatar.png" # Path to your avatar image
  bio: "A brief bio of Shao Cheng"
  location: "City, Country" # Your location (optional)
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/yourusername"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/yourlinkedin"
    # Add more social links here

# Theme and appearance
theme: "al-folio"

# Markdown options
markdown: kramdown
highlighter: rouge

# Collections (e.g., publications, projects, CV)
collections:
  publications:
    output: true
  projects:
    output: true
  # Add any other collections you need

# Defaults for markdown files (useful for automatic front-matter)
defaults:
  - scope:
      path: "" # Applies to all files in the project
    values:
      layout: "page"
  - scope:
      path: "_posts"
    values:
      layout: "post"
  - scope:
      path: "_publications"
    values:
      layout: "publication"

# Plugins (GitHub Pages safe list)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-scholar

# Exclude files from the site
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md

# Pagination settings (if using a blog or news posts)
paginate: 5
paginate_path: "/posts/page:num/"

# Other options (you can customize this further as per al-folio's documentation)
# Enable MathJax for LaTeX-style equations
mathjax: true

# Enable GitHub buttons (like fork, star, etc.)
github_buttons: true

# Social media settings
share:
  facebook: true
  twitter: true
  linkedin: true
  reddit: true

# SEO settings
seo:
  title_separator: "-"
  twitter:
    username: ""
